### ISSUE TITLE
Error generating synthetic dataset: Wrong arguments

### ISSUE THREAD

**Issue by jackychen651** [Moreno98/Vision-Language-Bias-Control#1]
Hi,

When I run the `generate_synthetic_dataset` file, I encountered the following error:
```
Traceback (most recent call last):
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/generate_synthetic_dataset.py", line 53, in <module>
    run()
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/generate_synthetic_dataset.py", line 27, in run
    device = device
TypeError: load_diffusion_model() got an unexpected keyword argument 'args'
```
So I changed the original code into:
```
diffae, DDIM_conf = utils.load_diffusion_model(
        opt = args,
        device = device
    )
```
But I got another error:
```
Traceback (most recent call last):
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/generate_synthetic_dataset.py", line 53, in <module>
    run()
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/generate_synthetic_dataset.py", line 27, in run
    device = device
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/lib/utils.py", line 51, in load_diffusion_model
    conf = ffhq256_autoenc_latent(timesteps=opt['diffusion_timesteps'])
TypeError: 'Namespace' object is not subscriptable
```
Any solutions?

Cheers,
Xiao Chen

**Comment by Moreno98** [comment]
Hello,
Yes, I did not propagate some changes I made to the code structure in all scripts. 
I updated the code with the correct version.

Thanks for catching it.

**Comment by jackychen651** [comment]
Hi,

The updated code is now running. Thanks a lot.

Best regards,
Xiao Chen
