### ISSUE TITLE
Image size incompatibility error

### ISSUE THREAD

**Issue by jackychen651** [Moreno98/Vision-Language-Bias-Control#2]
Hi,

 When I run the ```pseudo_labelling.py``` file, the following error was presented:
```
Traceback (most recent call last):
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/pseudo_labelling.py", line 133, in <module>
    run()
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/pseudo_labelling.py", line 99, in run
    face = face_detector.single_image(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/chenxiao/conda/envs/vlbc/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/utils/face_detector.py", line 28, in single_image
    bboxes = self.face_detector.detect_from_batch((image*255).unsqueeze(0))[0][0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/lib/sfd/sfd_detector.py", line 24, in detect_from_batch
    bboxlists = batch_detect(self.face_detector, tensor, device=self.device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/remote-home/chenxiao/Vision-Language-Bias-Control-main/lib/sfd/detect.py", line 41, in batch_detect
    BB, CC, HH, WW = img_batch.size()
    ^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
```

To solve this bug, the following code in ```utils/face_detector.py``` in line 28
```
bboxes = self.face_detector.detect_from_batch((image * 255.unsqueeze(0)))[0][0]
```
was changed to
```
bboxes = self.face_detector.detect_from_batch((image * 255))[0][0]
```
Am I right?

Best regards,
Xiao Chen

**Comment by Moreno98** [comment]
Hi, yes, I updated the code to fix this error.

Thanks.
